language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER invoicify WITH PASSWORD 'admin';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: lHXzcvD4bABrx2bqfsNr3+7MGyilno+scdtvpq2v2675nhXFfQa/XfgOOMbmPPQxldj0IaPqGSwwc/Vm9Gh5xA514FtwqjMjfLnFPq8F/zhvq3gp43O61E90UkmL6ccbQvjV00NctxvLBgzcwQCkN4BnUeeTyQTgGq9buBYwhmxlFkze0i0Z6jgtsr8RTQTimduh4O8+nLBWPMe0D6W9ScJmIMt3j0Fxt66+vxtp64CstnyahqXx7PC/2hsDV2WwtBXCGebGQ0XvPsuWMnSNgEjHB7gxdOsXkkum0nCzcr3fIrpRWYNWvnVbckawcoPiOAzOy+VaHeZUHvuvOcWo4UVt0Mp/jV+gYuad3Oa8lmGP5vUNYjZB5I3tcV69oTOkxuQxyX9hru1nx7mIm/z6U2PYjC/UHaCz/eVEreUPjdH5DsIfq1/SlDVxR2xr3ytiVbsOsCI9YtCCzzV75AJID8ZUo1xzVxtiT74LTdWmjXWWLL0ZYXfI+M7OYBGGl8PAjVucDDd/eGYIBJdysMRMeW2W2LydjLB9sWE/pk3cg/K8dkwStlvwTInIw6Ho4u+DQkwbUQ32uS5GDmtc+3GSGmG4Wd+7vFRkQVHHHMjbs4hCiNlJ/dzn0jnrAGvO4eES+6Cr9S4eNQyD1J9ADjTENmGMtlgzl7cLjj/7Sp/9g8s=
