language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER invoicify WITH PASSWORD 'admin';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: HfWMf9SYQBG+y/QcQR5YkwoBoRxSxVMxYCwE5NzmjCRLPZFzAsBipZjwSiLP8P3mKwIBUrn/V3wJxzuJSTU5QnxgMMJrc6NwFc9PsnCImCMQP8FBubINZ/WeHdHKpl91aOV7J7hJC6gfzUEO0MpnMAQqYhGJ3X7UGleCd0/UBU6KNw2CyRriOzLGo9P+e2tlNBUoV4OVsvkNQLbMVwSzJwxa+cGFiIVD/kUhGwCf2/ss9xDV5ZNVXIUwr9sQsuf9Qu22XuDV24TV4pGqBvikAg8W+gpl3pF/peO/cQldsA6Kl7WRr4Mv8PQ3ZPpFDR9kRTaGmK43h3OtRvedRJPPeIIYcvA6nk+2VAhCoO1FE1Hifo+AjL+25wfHIw/DUM/l/Q8V6MioNiiIg+WxFCHNXAenlcujozCb4pccJVIoWnYv0LHpwsEtMU7cJ1mEk+uGATiRPKURgctjcN30YQ8HwgDRxGXFRpVCLsQACK4IU/6XPL+J619Vrvb9ECYwI6U3sx/uB2fNWqmYAq5BsTubIk12OSdcdIOqPLZDXUSMmduovH/fMAFLUutDYlQ1vL1N8ntTvB66vegbxOyu4IH8zoMaCi9h2y/0Zxx8WzvhnCx10FxTxnBXXCaeIDfpScWr3Uv9gG77snY3vDQMA8JVkrsgyl7Jj6TjDkl6pnJD6nI=
