language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER invoicify WITH PASSWORD 'admin';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: q9jyMDP627mcxn+c11llIxaerJXvDEnp6K1drhwl0vUp48YCks+e2LMS+Jt9GRw5E4K+j/XTvlmvkXDXf0kZZsAp7jaWIsBTMx3YBB4g/ep8FkAY4tbwJ8g7hBotfUkEDiUwVovHWG9/L+VxFPvTXqIFlnF75OZXxJHIIgMGBGDn+u7Xc8wmQ3Cn5ABWLLtbpYGs98vQ/AG/9HcvWNkVWw+euUfDvYzhvfdEgJ/SSJjyOxW0SawqqXWCK3/OB76GxwB0r+f3juHq/GvAe7SvF2vHPR0pIc05OXYXNkS/xM3NFzS9LtkJKFgkuY8H/3QicnrHCTMkWHH21314KSUVK/vmT5jaJr0T7oHrm1c5DsYagF3gOvTzmn28xRYsdGMoNz7cmQInGdiUwgLPGEw/jZYWazR5xDrF/yZiljVEzNjDDqNHypauqLfdZUvi3uu4G38Df56QTtE1jz5o3mzFEvmLhizNEjJO5z5LjXtpoWTIZT8smdDhml8KgiIxVQ8G1cN833mIncSIs7Sn6BngKCsXxKnZBHHuBtqZiawEIRebKgRRW+F8cHAU6HiUhNjaEx11hCj7wGcjeptwZzYldxjkwhH/vQ2P706lzdZJZb+xYvoVbQFGYRLdDIRvNmnbLk1x+1fQ35i+c+OExRm7IO1OT0+xxtwVn1XQtFkDU+o=
